In [15]:
import pandas as pd
import numpy as np
from linearmodels.iv import IV2SLS

In [16]:
def flip_dataframe(file_path):
    # Read the CSV without interpreting the first row as headers.
    df = pd.read_csv(file_path, header=None)
    # Transpose the DataFrame.
    df_transposed = df.T
    # Set the first row of the transposed DataFrame as header.
    df_transposed.columns = df_transposed.iloc[0]
    # Drop the first row (now redundant as header) and reset the index.
    df_transposed = df_transposed.drop(df_transposed.index[0]).reset_index(drop=True)
    return df_transposed

# Example usage for one of your files:
dbs = flip_dataframe("../data/dbs ratios.csv")
ocbc = flip_dataframe("../data/ocbc ratios.csv")
uob = flip_dataframe("../data/uob ratios.csv")

In [ ]:
#dbs.to_csv('../data/dbs_clean.csv', index=False)
#ocbc.to_csv('../data/ocbc_clean.csv', index=False)
#uob.to_csv('../data/uob_clean.csv', index=False)

In [18]:
dbs['bank'] = 'DBS'
ocbc['bank'] = 'OCBC'
uob['bank'] = 'UOB'
# Concatenate the three banks into one DataFrame
df_banks = pd.concat([dbs, ocbc, uob], ignore_index=True)

df_banks.rename(columns={df_banks.columns[0]: 'Year'}, inplace=True)
df_banks['Year'] = pd.to_datetime(df_banks['Year'], format='%d/%m/%Y', errors='coerce').dt.year.astype(int)

df_banks = df_banks.apply(lambda col: col if col.name == 'bank' 
                          else pd.to_numeric(col.astype(str).str.replace(',', ''), errors='coerce'))

In [19]:
print(df_banks.columns.tolist())

['Year', ' ∟ Total assets (thousands USD)', ' ∟ Total equity / Total assets (%)', ' ∟ Total operating expenses (thousands USD)', ' ∟ Net interest margin (average total earning assets) (%)', ' ∟ Net interest income (expenses) / Average total assets (%)', ' ∟ Non-interest income / Average total assets (%)', ' ∟ Non-interest expenses / Average total assets (%)', ' ∟ Pre-tax operating profit / Average total assets (%)', ' ∟ Non-operating income (expense) & taxes / Average total assets (%)', ' ∟ Return on average assets (ROAA) (%)', ' ∟ Return on average equity (ROAE) (%)', ' ∟ Dividends related to the period / Net income (Dividend pay-out ratio) (%)', ' ∟ Net profit post dividends / Average Equity (%)', ' ∟ Other non-operating income (expense) / Net income (%)', ' ∟ Cost-to-income (Efficiency) ratio (%)', ' ∟ Recurring earning power (Pre-impairment operating profit / Average total assets) (%)', 'bank', ' ∟ Total assets', ' ∟ Total operating expenses']

In [20]:
# Create a mask for UOB rows
mask_uob = df_banks['bank'] == 'UOB'

# --- For Total Assets ---
# If your desired column is already named 'total assets (thousands USD)' and UOB's asset data is in 'Total Assets'
if ' ∟ Total assets' in df_banks.columns:
    # For UOB rows, fill missing values in the main asset column using the extra column
    if ' ∟ Total assets (thousands USD)' in df_banks.columns:
        df_banks.loc[mask_uob, ' ∟ Total assets (thousands USD)'] = df_banks.loc[mask_uob, ' ∟ Total assets (thousands USD)'].fillna(
            df_banks.loc[mask_uob, ' ∟ Total assets']
        )
    else:
        # If the desired column doesn't exist for UOB, just copy the values
        df_banks.loc[mask_uob, ' ∟ Total assets (thousands USD)'] = df_banks.loc[mask_uob, ' ∟ Total assets']
    # Drop the extra column
    df_banks.drop(columns=[' ∟ Total assets'], inplace=True)

# --- For Total Operating Expenses ---
# Assume the desired column is named 'total operating expenses (thousands USD)' and UOB's data is stored in an extra column, say 'Total Operating Expenses'
if ' ∟ Total operating expenses' in df_banks.columns:
    if ' ∟ Total operating expenses (thousands USD)' in df_banks.columns:
        df_banks.loc[mask_uob, ' ∟ Total operating expenses (thousands USD)'] = df_banks.loc[mask_uob, ' ∟ Total operating expenses (thousands USD)'].fillna(
            df_banks.loc[mask_uob, ' ∟ Total operating expenses']
        )
    else:
        df_banks.loc[mask_uob, ' ∟ Total operating expenses (thousands USD)'] = df_banks.loc[mask_uob, ' ∟ Total operating expenses']
    df_banks.drop(columns=[' ∟ Total operating expenses'], inplace=True)

# Verify the change
df_banks

,Year,∟ Total assets (thousands USD),∟ Total equity / Total assets (%),∟ Total operating expenses (thousands USD),∟ Net interest margin (average total earning assets) (%),∟ Net interest income (expenses) / Average total assets (%),∟ Non-interest income / Average total assets (%),∟ Non-interest expenses / Average total assets (%),∟ Pre-tax operating profit / Average total assets (%),∟ Non-operating income (expense) & taxes / Average total assets (%),∟ Return on average assets (ROAA) (%),∟ Return on average equity (ROAE) (%),∟ Dividends related to the period / Net income (Dividend pay-out ratio) (%),∟ Net profit post dividends / Average Equity (%),∟ Other non-operating income (expense) / Net income (%),∟ Cost-to-income (Efficiency) ratio (%),∟ Recurring earning power (Pre-impairment operating profit / Average total assets) (%),bank
0,2024,608115141.0,8.32,6646328.0,2.07,1.84,1.01,1.23,1.64,-0.17,1.44,17.23,55.87,7.60,2.24,40.55,1.69,DBS
1,2023,560671177.0,8.42,6294555.0,2.04,1.84,0.88,1.18,1.55,-0.18,1.36,16.87,46.11,9.09,0.89,41.17,1.60,DBS
2,2022,552854366.0,7.68,5272943.0,1.71,1.53,0.78,1.04,1.31,-0.13,1.15,14.28,45.20,7.82,3.58,42.96,1.32,DBS
3,2021,507563087.0,8.41,4859806.0,1.42,1.26,0.86,0.99,1.16,-0.12,1.02,12.12,38.39,7.47,2.72,46.30,1.14,DBS
4,2020,491595199.0,8.41,4657742.0,1.63,1.48,0.90,1.47,0.87,-0.13,0.77,8.94,54.46,4.07,-3.76,42.20,1.37,DBS
5,2019,429740213.0,8.95,4645190.0,1.84,1.70,0.87,1.23,1.34,-0.21,1.14,12.65,59.65,5.10,-0.08,43.03,1.47,DBS
6,2018,403539717.0,9.06,4259965.0,1.82,1.68,0.79,1.21,1.25,-0.20,1.06,11.34,54.41,5.17,-0.94,44.10,1.38,DBS
7,2017,387334275.0,9.62,3894209.0,1.70,1.56,0.90,1.39,1.04,-0.17,0.90,9.31,16.94,7.73,-3.95,42.41,1.41,DBS
8,2016,332966880.0,9.75,3437738.0,1.69,1.56,0.89,1.27,1.08,-0.25,0.93,9.71,17.22,8.04,-9.95,43.28,1.39,DBS
9,2015,323809318.0,9.35,3465592.0,1.72,1.58,0.85,1.25,1.18,-0.16,1.02,11.00,16.49,9.19,0.20,44.86,1.34,DBS
10,2014,333509423.0,9.12,3277076.0,1.64,1.50,0.83,1.18,1.16,-0.16,0.99,10.75,16.63,8.96,0.93,44.11,1.30,DBS
11,2013,317717542.0,9.37,3096499.0,1.62,1.48,0.93,1.23,1.19,-0.15,1.03,10.52,17.86,8.64,1.06,43.06,1.37,DBS
12,2012,288543516.0,10.20,2953821.0,1.70,1.52,0.93,1.16,1.33,-0.14,1.16,11.64,17.14,9.64,2.51,42.45,1.41,DBS
13,2011,262048889.0,9.70,2539402.0,1.79,1.55,0.90,1.27,1.20,-0.12,1.05,9.94,20.85,7.87,2.40,43.28,1.39,DBS
14,2010,220271742.0,11.67,2270963.0,1.86,1.59,0.98,1.37,0.85,-0.51,0.69,5.94,34.35,3.90,-49.89,42.01,1.49,DBS
15,2009,184298135.0,11.41,1855494.0,1.98,1.73,0.83,1.56,0.98,-0.13,0.86,8.33,57.18,3.57,-2.65,39.51,1.55,DBS
16,2008,178375490.0,9.35,1844775.0,2.00,1.76,0.70,1.30,1.06,-0.29,0.87,9.07,56.66,3.93,-12.25,44.06,1.38,DBS
17,2007,161645150.0,9.94,1816542.0,2.19,1.91,0.95,1.28,1.41,-0.45,1.14,11.08,43.08,6.31,-15.23,42.52,1.64,DBS
18,2006,128664923.0,10.66,1544328.0,2.13,1.90,0.92,1.38,1.59,-0.16,1.29,12.07,33.55,8.02,10.99,44.41,1.57,DBS
19,2005,108282660.0,10.65,1217402.0,1.81,1.63,0.77,1.26,0.74,-0.60,0.55,5.13,76.24,1.22,-73.71,46.82,1.28,DBS
20,2023,440940400.0,9.55,4039132.0,1.86,1.69,0.67,1.05,1.48,-0.05,1.26,13.27,50.22,6.61,13.31,39.64,1.42,OCBC
21,2022,414193058.0,9.41,3675442.0,1.53,1.40,0.64,0.99,1.21,-0.02,1.03,10.56,44.69,5.84,16.49,44.18,1.14,OCBC
22,2021,401114907.0,10.02,3528150.0,1.20,1.10,0.85,1.06,1.07,0.05,0.95,9.54,36.57,6.05,18.38,45.90,1.06,OCBC
23,2020,394368814.0,9.82,3359806.0,1.27,1.18,0.79,1.27,0.82,0.04,0.74,7.47,51.88,3.60,16.93,44.49,1.09,OCBC
24,2019,364972194.0,9.88,3444207.0,1.42,1.32,0.91,1.15,1.21,-0.03,1.05,10.92,40.97,6.45,13.03,43.44,1.26,OCBC
25,2018,342572534.0,9.28,3095634.0,1.37,1.28,0.79,0.98,1.20,-0.08,1.01,10.98,34.95,7.14,11.31,44.21,1.16,OCBC
26,2017,340369841.0,9.18,3042185.0,1.36,1.25,0.94,1.08,1.21,-0.09,1.02,10.84,35.15,7.03,9.71,42.92,1.25,OCBC
27,2016,283401479.0,9.67,2635266.0,1.37,1.26,0.81,1.13,1.07,-0.03,0.91,9.50,42.07,5.50,13.77,46.06,1.12,OCBC
28,2015,275966926.0,9.51,2604442.0,1.44,1.31,0.86,1.03,1.22,-0.10,1.04,11.52,37.16,7.24,8.29,42.94,1.24,OCBC
29,2014,303660048.0,8.52,2463207.0,1.41,1.28,0.94,0.98,1.29,-0.14,1.10,13.09,34.42,8.59,3.73,39.57,1.34,OCBC
30,2013,267484699.0,8.30,2197236.0,1.34,1.22,0.84,0.96,1.12,-0.16,0.94,10.46,42.26,6.04,2.57,42.54,1.18,OCBC
31,2012,241882674.0,9.70,2189965.0,1.42,1.31,1.41,1.03,1.73,-0.21,1.49,15.76,27.57,11.42,2.34,34.33,1.79,OCBC
32,2011,213544708.0,9.14,1870977.0,1.47,1.35,0.85,1.04,1.17,-0.17,0.98,10.11,44.95,5.57,1.45,43.77,1.23,OCBC
33,2010,178014606.0,10.31,1720650.0,1.54,1.39,1.05,1.12,1.36,-0.17,1.16,10.77,44.30,6.00,3.26,42.85,1.40,OCBC
34,2009,138449153.0,11.21,1273686.0,1.66,1.50,1.03,1.09,1.35,-0.29,1.15,10.68,45.81,5.79,-7.28,37.62,1.58,OCBC
35,2008,126031932.0,10.23,1283138.0,1.71,1.56,0.89,1.14,1.17,-0.27,1.04,10.51,49.86,5.27,-13.36,42.31,1.41,OCBC
36,2007,121154097.0,9.64,1171511.0,1.52,1.38,1.17,0.97,1.56,-0.23,1.34,13.94,41.36,8.17,-1.18,40.73,1.51,OCBC
37,2006,98578660.0,9.58,874809.0,1.37,1.25,1.22,0.95,1.73,-0.05,1.47,15.06,35.51,9.71,14.48,37.97,1.53,OCBC
38,2005,80946049.0,10.01,692368.0,1.29,1.19,0.93,0.89,1.27,-0.19,1.04,10.36,17.08,8.59,3.82,40.35,1.26,OCBC
39,2023,397027158.0,8.88,4733050.0,2.17,1.88,0.83,1.37,1.34,-0.23,1.11,12.71,46.83,6.76,-0.42,44.79,1.50,UOB
40,2022,375026021.0,8.65,3929793.0,1.97,1.73,0.67,1.24,1.20,-0.21,0.95,10.60,43.86,5.95,4.06,45.64,1.31,UOB
41,2021,339811361.0,9.33,3190797.0,1.61,1.43,0.76,1.09,1.11,-0.19,0.92,9.73,40.59,5.78,-0.15,44.06,1.23,UOB
42,2020,326612214.0,9.53,3164662.0,1.61,1.44,0.75,1.16,0.85,-0.33,0.70,7.24,64.95,2.54,-26.62,45.58,1.19,UOB
43,2019,300184524.0,9.86,3319624.0,1.83,1.66,0.88,1.25,1.31,-0.18,1.10,11.23,47.80,5.86,1.96,44.59,1.40,UOB
44,2018,284358411.0,9.74,2933261.0,1.85,1.67,0.77,1.17,1.29,-0.19,1.08,10.74,47.59,5.63,2.36,43.94,1.37,UOB
45,2017,268286965.0,10.33,3013041.0,1.77,1.58,0.95,1.34,1.20,-0.22,0.98,9.72,33.85,6.43,1.20,45.49,1.38,UOB
46,2016,235101730.0,9.72,2555831.0,1.73,1.52,0.94,1.30,1.15,-0.21,0.95,9.72,36.20,6.20,-0.48,45.86,1.33,UOB
47,2015,223503219.0,9.79,2544001.0,1.84,1.58,1.00,1.34,1.24,-0.20,1.03,10.61,44.78,5.86,0.62,44.78,1.42,UOB
48,2014,232147236.0,9.71,2381261.0,1.78,1.54,0.97,1.26,1.29,-0.15,1.10,11.59,36.38,7.37,3.28,42.31,1.45,UOB
49,2013,224633742.0,9.35,2290507.0,1.80,1.53,0.97,1.23,1.33,-0.14,1.13,11.67,36.45,7.42,5.85,43.17,1.42,UOB
50,2012,206701681.0,9.99,2251542.0,1.90,1.60,1.04,1.31,1.37,-0.18,1.15,11.65,33.47,7.75,3.06,42.54,1.52,UOB
51,2011,182177088.0,9.77,1892009.0,1.96,1.63,0.89,1.30,1.25,-0.19,1.04,10.45,46.39,5.60,1.86,43.25,1.43,UOB
52,2010,165977083.0,10.13,1761444.0,2.13,1.77,1.07,1.35,1.60,-0.13,1.36,13.32,28.39,9.54,8.15,40.01,1.70,UOB
53,2009,132234843.0,10.32,1485423.0,2.36,1.99,0.94,1.73,1.25,-0.16,1.04,11.02,47.03,5.84,5.06,38.58,1.80,UOB
54,2008,127112868.0,8.59,1431854.0,2.38,2.00,0.92,1.49,1.39,-0.33,1.10,11.75,49.82,5.89,-3.60,39.41,1.77,UOB
55,2007,121392092.0,10.13,1408284.0,2.11,1.77,1.12,1.30,1.64,-0.30,1.29,12.47,54.45,5.68,3.23,41.72,1.69,UOB
56,2006,105157543.0,10.65,1139943.0,2.10,1.77,1.36,1.23,2.07,-0.18,1.71,16.21,37.27,10.17,10.29,36.43,1.99,UOB
57,2005,87172679.0,10.49,891672.0,1.90,1.62,0.96,1.13,1.52,-0.25,1.19,11.38,62.87,4.22,6.12,39.67,1.56,UOB

### digital payment

In [21]:
xls = pd.ExcelFile("../data/Retail_Payment_Analysis.xlsx")
raw_data = xls.parse('Raw Data')

atm as BNDP and rest as TTP

In [22]:
raw_data['Category'] = raw_data['Instrument'].apply(lambda x: 'BNDP' 
                                                    if 
                                                        'ATM Withdrawals' in x or 
                                                        'CNP Card Payments (Credit)' in x or
                                                        'CNP Card Payments (Debit)' in x or
                                                        'FAST' in x or 
                                                        'Inter-bank GIRO' in x or 
                                                        'POS Card Payments (Credit)' in x or 
                                                        'POS Card Payments (Debit)' in x or 
                                                        'Singapore Dollar Cheque Clearing' in x or 
                                                        'Stored Value Facilities' in x or 
                                                        'US Dollar Cheque Clearing' in x 
                                                    else 'TPP')
print("Unique categories in raw_data:", raw_data['Instrument'].unique())

Unique categories in raw_data: ['ATM Withdrawals' 'CNP Card Payments (Credit)'
 'CNP Card Payments (Debit)' 'FAST' 'Inter-bank GIRO'
 'POS Card Payments (Credit)' 'POS Card Payments (Debit)'
 'Singapore Dollar Cheque Clearing' 'Stored Value Facilities'
 'US Dollar Cheque Clearing']

In [23]:

agg = raw_data.groupby(['Year', 'Category'])['Value'].sum().unstack()

# Rename columns for clarity and compute logs:
agg = agg.rename(columns={'BNDP': 'bank_involved', 'TPP': 'third_party'})
agg['LNBDP'] = np.log(agg['bank_involved'])
#agg['LNTPP'] = np.log(agg['third_party'])
agg = agg.reset_index()[['Year', 'LNBDP']]
agg['Year'] = agg['Year'].astype(int)
agg

Category  Year      LNBDP
0         2014  14.019855
1         2015  14.011957
2         2016  14.017553
3         2017  14.001045
4         2018  14.013493
5         2019  14.099713
6         2020  13.936822
7         2021  13.930941
8         2022  13.934624
9         2023  13.939717

# Combining dataset

In [24]:
df_banks['SIZE'] = np.log(df_banks[' ∟ Total assets (thousands USD)'])
df_banks['RISK'] = df_banks[' ∟ Total equity / Total assets (%)'] / df_banks[' ∟ Total assets (thousands USD)']
df_banks['COST'] = df_banks[' ∟ Total operating expenses (thousands USD)'] / df_banks[' ∟ Total assets (thousands USD)']

In [25]:
print("df_banks Year values and type:")
print(df_banks['Year'].head())
print(df_banks['Year'].dtype)

print("\nagg Year values and type:")
print(agg['Year'].head())
print(agg['Year'].dtype)

df_banks Year values and type:
0    2024
1    2023
2    2022
3    2021
4    2020
Name: Year, dtype: int64
int64

agg Year values and type:
0    2014
1    2015
2    2016
3    2017
4    2018
Name: Year, dtype: int64
int64

merge bank with digital payment

In [26]:
# Merge on 'Year'
df_panel = pd.merge(df_banks, agg, on='Year', how='left')

# Set a multi-index with bank and year for panel data operations
df_panel = df_panel.set_index(['bank', 'Year']).sort_index()
df_panel

            ∟ Total assets (thousands USD)  \
bank Year
DBS  2005                      108282660.0
     2006                      128664923.0
     2007                      161645150.0
     2008                      178375490.0
     2009                      184298135.0
     2010                      220271742.0
     2011                      262048889.0
     2012                      288543516.0
     2013                      317717542.0
     2014                      333509423.0
     2015                      323809318.0
     2016                      332966880.0
     2017                      387334275.0
     2018                      403539717.0
     2019                      429740213.0
     2020                      491595199.0
     2021                      507563087.0
     2022                      552854366.0
     2023                      560671177.0
     2024                      608115141.0
OCBC 2005                       80946049.0
     2006                       98578660.0
     2007                      121154097.0
     2008                      126031932.0
     2009                      138449153.0
     2010                      178014606.0
     2011                      213544708.0
     2012                      241882674.0
     2013                      267484699.0
     2014                      303660048.0
     2015                      275966926.0
     2016                      283401479.0
     2017                      340369841.0
     2018                      342572534.0
     2019                      364972194.0
     2020                      394368814.0
     2021                      401114907.0
     2022                      414193058.0
     2023                      440940400.0
UOB  2005                       87172679.0
     2006                      105157543.0
     2007                      121392092.0
     2008                      127112868.0
     2009                      132234843.0
     2010                      165977083.0
     2011                      182177088.0
     2012                      206701681.0
     2013                      224633742.0
     2014                      232147236.0
     2015                      223503219.0
     2016                      235101730.0
     2017                      268286965.0
     2018                      284358411.0
     2019                      300184524.0
     2020                      326612214.0
     2021                      339811361.0
     2022                      375026021.0
     2023                      397027158.0

            ∟ Total equity / Total assets (%)  \
bank Year
DBS  2005                               10.65
     2006                               10.66
     2007                                9.94
     2008                                9.35
     2009                               11.41
     2010                               11.67
     2011                                9.70
     2012                               10.20
     2013                                9.37
     2014                                9.12
     2015                                9.35
     2016                                9.75
     2017                                9.62
     2018                                9.06
     2019                                8.95
     2020                                8.41
     2021                                8.41
     2022                                7.68
     2023                                8.42
     2024                                8.32
OCBC 2005                               10.01
     2006                                9.58
     2007                                9.64
     2008                               10.23
     2009                               11.21
     2010                               10.31
     2011                                9.14
     2012                                9.70
     2013                                8.30
     2014                                8.52
     2015                                9.51
     2016                                9.67
     2017                                9.18
     2018                                9.28
     2019                                9.88
     2020                                9.82
     2021                               10.02
     2022                                9.41
     2023                                9.55
UOB  2005                               10.49
     2006                               10.65
     2007                               10.13
     2008                                8.59
     2009                               10.32
     2010                               10.13
     2011                                9.77
     2012                                9.99
     2013                                9.35
     2014                                9.71
     2015                                9.79
     2016                                9.72
     2017                               10.33
     2018                                9.74
     2019                                9.86
     2020                                9.53
     2021                                9.33
     2022                                8.65
     2023                                8.88

            ∟ Total operating expenses (thousands USD)  \
bank Year
DBS  2005                                    1217402.0
     2006                                    1544328.0
     2007                                    1816542.0
     2008                                    1844775.0
     2009                                    1855494.0
     2010                                    2270963.0
     2011                                    2539402.0
     2012                                    2953821.0
     2013                                    3096499.0
     2014                                    3277076.0
     2015                                    3465592.0
     2016                                    3437738.0
     2017                                    3894209.0
     2018                                    4259965.0
     2019                                    4645190.0
     2020                                    4657742.0
     2021                                    4859806.0
     2022                                    5272943.0
     2023                                    6294555.0
     2024                                    6646328.0
OCBC 2005                                     692368.0
     2006                                     874809.0
     2007                                    1171511.0
     2008                                    1283138.0
     2009                                    1273686.0
     2010                                    1720650.0
     2011                                    1870977.0
     2012                                    2189965.0
     2013                                    2197236.0
     2014                                    2463207.0
     2015                                    2604442.0
     2016                                    2635266.0
     2017                                    3042185.0
     2018                                    3095634.0
     2019                                    3444207.0
     2020                                    3359806.0
     2021                                    3528150.0
     2022                                    3675442.0
     2023                                    4039132.0
UOB  2005                                     891672.0
     2006                                    1139943.0
     2007                                    1408284.0
     2008                                    1431854.0
     2009                                    1485423.0
     2010                                    1761444.0
     2011                                    1892009.0
     2012                                    2251542.0
     2013                                    2290507.0
     2014                                    2381261.0
     2015                                    2544001.0
     2016                                    2555831.0
     2017                                    3013041.0
     2018                                    2933261.0
     2019                                    3319624.0
     2020                                    3164662.0
     2021                                    3190797.0
     2022                                    3929793.0
     2023                                    4733050.0

            ∟ Net interest margin (average total earning assets) (%)  \
bank Year
DBS  2005                                               1.81
     2006                                               2.13
     2007                                               2.19
     2008                                               2.00
     2009                                               1.98
     2010                                               1.86
     2011                                               1.79
     2012                                               1.70
     2013                                               1.62
     2014                                               1.64
     2015                                               1.72
     2016                                               1.69
     2017                                               1.70
     2018                                               1.82
     2019                                               1.84
     2020                                               1.63
     2021                                               1.42
     2022                                               1.71
     2023                                               2.04
     2024                                               2.07
OCBC 2005                                               1.29
     2006                                               1.37
     2007                                               1.52
     2008                                               1.71
     2009                                               1.66
     2010                                               1.54
     2011                                               1.47
     2012                                               1.42
     2013                                               1.34
     2014                                               1.41
     2015                                               1.44
     2016                                               1.37
     2017                                               1.36
     2018                                               1.37
     2019                                               1.42
     2020                                               1.27
     2021                                               1.20
     2022                                               1.53
     2023                                               1.86
UOB  2005                                               1.90
     2006                                               2.10
     2007                                               2.11
     2008                                               2.38
     2009                                               2.36
     2010                                               2.13
     2011                                               1.96
     2012                                               1.90
     2013                                               1.80
     2014                                               1.78
     2015                                               1.84
     2016                                               1.73
     2017                                               1.77
     2018                                               1.85
     2019                                               1.83
     2020                                               1.61
     2021                                               1.61
     2022                                               1.97
     2023                                               2.17

            ∟ Net interest income (expenses) / Average total assets (%)  \
bank Year
DBS  2005                                               1.63
     2006                                               1.90
     2007                                               1.91
     2008                                               1.76
     2009                                               1.73
     2010                                               1.59
     2011                                               1.55
     2012                                               1.52
     2013                                               1.48
     2014                                               1.50
     2015                                               1.58
     2016                                               1.56
     2017                                               1.56
     2018                                               1.68
     2019                                               1.70
     2020                                               1.48
     2021                                               1.26
     2022                                               1.53
     2023                                               1.84
     2024                                               1.84
OCBC 2005                                               1.19
     2006                                               1.25
     2007                                               1.38
     2008                                               1.56
     2009                                               1.50
     2010                                               1.39
     2011                                               1.35
     2012                                               1.31
     2013                                               1.22
     2014                                               1.28
     2015                                               1.31
     2016                                               1.26
     2017                                               1.25
     2018                                               1.28
     2019                                               1.32
     2020                                               1.18
     2021                                               1.10
     2022                                               1.40
     2023                                               1.69
UOB  2005                                               1.62
     2006                                               1.77
     2007                                               1.77
     2008                                               2.00
     2009                                               1.99
     2010                                               1.77
     2011                                               1.63
     2012                                               1.60
     2013                                               1.53
     2014                                               1.54
     2015                                               1.58
     2016                                               1.52
     2017                                               1.58
     2018                                               1.67
     2019                                               1.66
     2020                                               1.44
     2021                                               1.43
     2022                                               1.73
     2023                                               1.88

            ∟ Non-interest income / Average total assets (%)  \
bank Year
DBS  2005                                               0.77
     2006                                               0.92
     2007                                               0.95
     2008                                               0.70
     2009                                               0.83
     2010                                               0.98
     2011                                               0.90
     2012                                               0.93
     2013                                               0.93
     2014                                               0.83
     2015                                               0.85
     2016                                               0.89
     2017                                               0.90
     2018                                               0.79
     2019                                               0.87
     2020                                               0.90
     2021                                               0.86
     2022                                               0.78
     2023                                               0.88
     2024                                               1.01
OCBC 2005                                               0.93
     2006                                               1.22
     2007                                               1.17
     2008                                               0.89
     2009                                               1.03
     2010                                               1.05
     2011                                               0.85
     2012                                               1.41
     2013                                               0.84
     2014                                               0.94
     2015                                               0.86
     2016                                               0.81
     2017                                               0.94
     2018                                               0.79
     2019                                               0.91
     2020                                               0.79
     2021                                               0.85
     2022                                               0.64
     2023                                               0.67
UOB  2005                                               0.96
     2006                                               1.36
     2007                                               1.12
     2008                                               0.92
     2009                                               0.94
     2010                                               1.07
     2011                                               0.89
     2012                                               1.04
     2013                                               0.97
     2014                                               0.97
     2015                                               1.00
     2016                                               0.94
     2017                                               0.95
     2018                                               0.77
     2019                                               0.88
     2020                                               0.75
     2021                                               0.76
     2022                                               0.67
     2023                                               0.83

            ∟ Non-interest expenses / Average total assets (%)  \
bank Year
DBS  2005                                               1.26
     2006                                               1.38
     2007                                               1.28
     2008                                               1.30
     2009                                               1.56
     2010                                               1.37
     2011                                               1.27
     2012                                               1.16

generate lags and first differences for DIFF GMM estimation

In [27]:
# Here we demonstrate for ROA as the dependent variable.
df_panel['ROA'] = df_panel[" ∟ Return on average assets (ROAA) (%)"]
# Generate lagged ROA variables (lag 1 and lag 2)
df_panel['ROA_lag1'] = df_panel.groupby(level='bank')['ROA'].shift(1)
df_panel['ROA_lag2'] = df_panel.groupby(level='bank')['ROA'].shift(2)

# Compute first differences
df_panel['d_ROA'] = df_panel['ROA'] - df_panel['ROA_lag1']
# The lagged difference (for the endogenous regressor) is:
df_panel['d_ROA_lag1'] = df_panel['ROA_lag1'] - df_panel.groupby(level='bank')['ROA'].shift(2)

# Similarly, create differences for the control variables
for var in ['SIZE', 'RISK', 'COST', 'LNBDP']:
    df_panel[f'd_{var}'] = df_panel[var] - df_panel.groupby(level='bank')[var].shift(1)

# Drop rows with missing values (due to lags/differencing)
df_diff = df_panel.dropna()
df_panel.head()

            ∟ Total assets (thousands USD)  \
bank Year
DBS  2005                      108282660.0
     2006                      128664923.0
     2007                      161645150.0
     2008                      178375490.0
     2009                      184298135.0

            ∟ Total equity / Total assets (%)  \
bank Year
DBS  2005                               10.65
     2006                               10.66
     2007                                9.94
     2008                                9.35
     2009                               11.41

            ∟ Total operating expenses (thousands USD)  \
bank Year
DBS  2005                                    1217402.0
     2006                                    1544328.0
     2007                                    1816542.0
     2008                                    1844775.0
     2009                                    1855494.0

            ∟ Net interest margin (average total earning assets) (%)  \
bank Year
DBS  2005                                               1.81
     2006                                               2.13
     2007                                               2.19
     2008                                               2.00
     2009                                               1.98

            ∟ Net interest income (expenses) / Average total assets (%)  \
bank Year
DBS  2005                                               1.63
     2006                                               1.90
     2007                                               1.91
     2008                                               1.76
     2009                                               1.73

            ∟ Non-interest income / Average total assets (%)  \
bank Year
DBS  2005                                               0.77
     2006                                               0.92
     2007                                               0.95
     2008                                               0.70
     2009                                               0.83

            ∟ Non-interest expenses / Average total assets (%)  \
bank Year
DBS  2005                                               1.26
     2006                                               1.38
     2007                                               1.28
     2008                                               1.30
     2009                                               1.56

            ∟ Pre-tax operating profit / Average total assets (%)  \
bank Year
DBS  2005                                               0.74
     2006                                               1.59
     2007                                               1.41
     2008                                               1.06
     2009                                               0.98

            ∟ Non-operating income (expense) & taxes / Average total assets (%)  \
bank Year
DBS  2005                                              -0.60
     2006                                              -0.16
     2007                                              -0.45
     2008                                              -0.29
     2009                                              -0.13

            ∟ Return on average assets (ROAA) (%)  ...  LNBDP   ROA  ROA_lag1  \
bank Year                                          ...
DBS  2005                                    0.55  ...    NaN  0.55       NaN
     2006                                    1.29  ...    NaN  1.29      0.55
     2007                                    1.14  ...    NaN  1.14      1.29
     2008                                    0.87  ...    NaN  0.87      1.14
     2009                                    0.86  ...    NaN  0.86      0.87

           ROA_lag2  d_ROA  d_ROA_lag1    d_SIZE        d_RISK    d_COST  \
bank Year
DBS  2005       NaN    NaN         NaN       NaN           NaN       NaN
     2006       NaN   0.74         NaN  0.172466 -1.550283e-08  0.000760
     2007      0.55  -0.15        0.74  0.228192 -2.135814e-08 -0.000765
     2008      1.29  -0.27       -0.15  0.098487 -9.075205e-09 -0.000896
     2009      1.14  -0.01       -0.27  0.032664  9.493041e-09 -0.000274

           d_LNBDP
bank Year
DBS  2005      NaN
     2006      NaN
     2007      NaN
     2008      NaN
     2009      NaN

[5 rows x 29 columns]

# Run DIFF-GMM estimation using IV2SLS

In [28]:
# Model specification (for ROA as an example):
# d_ROA = α * d_ROA_lag1 + β1*d_SIZE + β2*d_RISK + β3*d_COST + β4*d_LNBDP + β5*d_LNTPP + error
# Instrument: Use ROA_lag2 as an instrument for d_ROA_lag1

# Define dependent variable, exogenous regressors, the endogenous regressor, and instruments
dependent = df_diff['d_ROA']
exog = df_diff[['d_SIZE', 'd_RISK', 'd_COST', 'd_LNBDP']]
endog = df_diff['d_ROA_lag1']
instruments = df_diff[['ROA_lag2']]

# Fit the IV regression (this serves as our DIFF-GMM estimator for illustration)
mod = IV2SLS(dependent, exog, endog, instruments)
res = mod.fit(cov_type='robust')
print(res.summary)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:                  d_ROA   R-squared:                      0.6813
Estimator:                    IV-2SLS   Adj. R-squared:                 0.6089
No. Observations:                  27   F-statistic:                    92.731
Date:                Sun, Mar 30 2025   P-value (F-stat)                0.0000
Time:                        02:03:48   Distribution:                  chi2(5)
Cov. Estimator:                robust

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
d_SIZE        -0.6829     0.5606    -1.2181     0.2232     -1.7816      0.4159
d_RISK     -3.454e+07  1.537e+07    -2.2481     0.0246  -6.466e+07  -4.427e+06
d_COST         110.88     45.249     2.4505     0.0143      22.197      199.57
d_LNBDP        1.3185     0.3306     3.9878     0.0001      0.6705      1.9665
d_ROA_lag1    -0.3348     0.5894    -0.5681     0.5700     -1.4901      0.8204
==============================================================================

Endogenous: d_ROA_lag1
Instruments: ROA_lag2
Robust Covariance (Heteroskedastic)
Debiased: False

we only have BDP and not TPP (or calssify)